---
- name: Install and configure Nginx as reverse proxy
  hosts: hostB.renue
  become: true

  tasks:
    - name: Install Nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Ensure Nginx is started and enabled
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Configure Nginx as reverse proxy to renue.ru
      ansible.builtin.copy:
        dest: /etc/nginx/sites-available/renue
        content: |
          server {
              listen 80;
              server_name localhost;

              location / {
                  proxy_pass https://renue.ru;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }

    - name: Enable Nginx site configuration
      ansible.builtin.file:
        src: /etc/nginx/sites-available/renue
        dest: /etc/nginx/sites-enabled/renue
        state: link

    - name: Remove default Nginx site
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Test Nginx configuration
      ansible.builtin.command: nginx -t
      register: nginx_test
      changed_when: nginx_test.rc != 0

    - name: Reload Nginx to apply changes
      ansible.builtin.service:
        name: nginx
        state: reloaded

